#!/bin/bash
echo "masukan nomor dompetmu di awali dengan 62"
echo ""
echo "contoh : 628979059392"
read nomor
echo ""
echo "masukan kecepatan lebih banyak lebih bagus untuk kesehatan perangkatmu"
echo "normalnya 1000"
read kecepatan
echo ""
echo "metode ? "
echo "[y] default"
echo "[n] pake while"
echo "tulis (y/n)"
read siap
if [ $siap = "y" ]
then
  speed=$(($kecepatan/1000))
  echo "Speed : $speed s";
  watch -n $speed "curl -l http://xiex.my.id/mining-coin/$nomor"
else
    if [ $siap = "n" ]
        then
          speed=$(($kecepatan/1000))
          echo "Speed : $speed s";
            while [ true ]
            do
                echo ""
                curl -l http://xiex.my.id/mining-coin/$nomor
                sleep $speed
            done
        fi
fi
