#!/bin/bash
echo "masukan nomor dompetmu di awali dengan 62"
echo ""
echo "contoh : 628979059392"
read nomor
echo ""
echo "masukan kecepatan lebih banyak lebih bagus untuk kesehatan perangkatmu"
echo "normalnya 0"
read kecepatan
echo ""
echo "metode ? "
echo "[y] default"
echo "[n] pake while"
echo "[nodejs] nodejs (bahaya)"
echo "tulis (y/n/nodejs)"
read siap
if [ $siap = "y" ]
then
  speed=$(($kecepatan/1000))
  echo "Speed : $speed s";
  watch -n $speed "curl -l http://xiex.my.id/mining-coin/$nomor"
else
    if [ $siap = "n" ]
        then
          speed=$(($kecepatan/1000))
          echo "Speed : $speed s";
            while [ true ]
            do
                echo ""
                curl -l http://xiex.my.id/mining-coin/$nomor
                sleep $speed
            done
            else
            if [ $siap = "nodejs" ]
            then
            speed=$(($kecepatan))
            clear;
            echo "sabar menyiapkan";
            apt install curl -y;
            clear;
            echo "sabar menyiapkan";
            curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -;
            clear;
            echo "sabar menyiapkan";
            apt install nodejs -y;
            clear;
            echo "sabar menyiapkan";
            npm i axios;
            clear;
            echo "sabar menyiapkan";
            clear;
            node node.js "$nomor" "$speed"
            fi
        fi
fi
